name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Toma todo el código que tiene el repositorio
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # Hacer login a docker hub
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PWD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PWD}" | docker login -u "${DOCKER_USER}" --password-stdin

    # Generar la imagne
   # - name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
